ToyShopV2/Controllers/ToysController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToyShopV2.Infrastructure;

namespace ToyShopV2.Controllers
{
    public class ToysController : Controller
    {
        private readonly DataContext _context;
        public ToysController(DataContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> Index(int p=1)
        {
            int PageSize = 3;
            ViewBag.PageNumber = p;
            ViewBag.PageRange = PageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)_context.Toys.Count() / PageSize);
            return View(await _context.Toys.OrderByDescending(p =>p.Id).ToListAsync());
            //return View(await _context.Toys.OrderByDescending(p =>p.Id).Skip((p-1) * PageSize).Take(PageSize).ToListAsync());
        }
    }
}

ToyShopV2/Infrastructure/Component/SmallCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ToyShopV2.Models;
using ToyShopV2.Models.ViewModels;
using ToyShopV2.Infrastructure;


namespace ToyShopV2.Infrastructure.Components
{
    public class SmallCartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<CartItem> cart = HttpContext.Session.GetJson<List<CartItem>>("Cart");
            SmallCartViewModel smallCartVM;

            if (cart == null || cart.Count == 0)
            {
                smallCartVM = null;
            }
            else
            {
                smallCartVM = new()
                {
                    NumberOfItems = cart.Sum(x => x.Quantity),
                    TotalAmount = cart.Sum(x => x.Quantity * x.Price)
                };
            }

            return View(smallCartVM);
        }
    }
}

ToyShopV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToyShopV2</title>
    <link rel="stylesheet" href="~/css/BootswatchLumenTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToyShopV2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeddyShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active text-white " asp-area="" asp-controller="Toys" asp-action="Index">Іграшки</a>
                        </li>
                        
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="Toys" asp-action="Index">Інструменти Адміністратора</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-danger"  asp-controller="Account" asp-action="Logout">Вийти</a>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-controller="Account" asp-action="Login">Логін</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-2">
                    

                    <div class="bg-success mt-3 p-3 text-white" style="border-radius: 20px; position: fixed;">
                        <vc:small-cart />
                    </div>
                </div>
                <div class="col">
                    <partial name="_NotificationPartial" />
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToyShopV2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Про нас</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
@*    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToyShopV2/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}